[package]
name = "subleq"
version = "0.1.0"
authors = ["Joyal Mathew <joyal.mathew@guilderlandschools.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
